import 'package:freezed_annotation/freezed_annotation.dart';

part 'weather_insight.freezed.dart';
part 'weather_insight.g.dart';

@freezed
abstract class WeatherInsight with _$WeatherInsight {
  const factory WeatherInsight({
    required SafetyStatus status,
    required String advice, // The human-readable explanation (AI or Heuristic)
    required DateTime timestamp,
    @Default(false) bool isAIInference, // Whether this was generated by Gemma
    String? insightId, // Composite ID to distinguish new vs same warnings
    @Default([])
    List<String> reasons, // Structured breakdown of why status changed
    @Default(0) int riskScore, // 0-100 numeric risk score for alerting priority
  }) = _WeatherInsight;

  factory WeatherInsight.fromJson(Map<String, dynamic> json) =>
      _$WeatherInsightFromJson(json);
}

enum SafetyStatus {
  @JsonValue('green')
  green,
  @JsonValue('yellow')
  yellow,
  @JsonValue('orange')
  orange,
  @JsonValue('red')
  red,
}

@freezed
abstract class SkipperSettings with _$SkipperSettings {
  const factory SkipperSettings({
    @Default(true) bool isAIEnabled,
    @Default(false) bool hasAcknowledgedAISafety, // NEW: Legal explicit ack
    @Default(3) int forecastWindowHours, // New: 3h, 6h, 12h
    @Default(SkipperThresholds()) SkipperThresholds thresholds,
    String? aiApiKey, // User's OpenRouter API key (masked in UI)
    @Default('meta-llama/llama-3.3-70b-instruct:free')
    String aiModelId, // Pinned primary model for explanations
  }) = _SkipperSettings;

  factory SkipperSettings.fromJson(Map<String, dynamic> json) =>
      _$SkipperSettingsFromJson(json);
}

@freezed
abstract class SkipperThresholds with _$SkipperThresholds {
  const factory SkipperThresholds({
    @Default(10.0) double windYellowMs, // Strong Breeze
    @Default(12.0) double windOrangeMs, // Near Gale start
    @Default(14.0) double windRedMs, // Small Craft Warning (FMI)
    @Default(1.0) double waveYellowM,
    @Default(1.5) double waveOrangeM,
    @Default(2.5) double waveRedM,
    @Default(2.0) double pressureDropThresholdHpa, // hPa/hour
  }) = _SkipperThresholds;

  factory SkipperThresholds.fromJson(Map<String, dynamic> json) =>
      _$SkipperThresholdsFromJson(json);
}
