import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:sakkoja/core/providers/core_providers.dart';
import 'package:sakkoja/features/navigation/data/daos/route_dao.dart';
import 'package:sakkoja/features/navigation/data/repositories/navigation_repository_impl.dart';
import 'package:sakkoja/features/navigation/domain/entities/route_entity.dart';
import 'package:sakkoja/features/navigation/domain/entities/waypoint_entity.dart';
import 'package:sakkoja/features/navigation/domain/repositories/navigation_repository.dart';
import 'package:sakkoja/features/navigation/domain/services/route_service.dart';
import 'package:sakkoja/features/navigation/presentation/controllers/route_planner_controller.dart';
import 'package:sakkoja/features/speed_limits/di/speed_limits_di.dart';

part 'navigation_providers.g.dart';

// DAO Provider
final routeDaoProvider = Provider<RouteDao>((ref) {
  final db = ref.watch(appDatabaseProvider);
  return db.routeDao;
});

// Repository Provider
final navigationRepositoryProvider = Provider<NavigationRepository>((ref) {
  final dao = ref.watch(routeDaoProvider);
  return NavigationRepositoryImpl(dao);
});

// Service Provider
final routeServiceProvider = Provider<RouteService>((ref) {
  final repo = ref.watch(navigationRepositoryProvider);
  final speedLimitRepo = ref.watch(speedLimitRepositoryProvider);
  return RouteService(repo, speedLimitRepo);
});

// Reactive Active Route
final activeRouteProvider = FutureProvider<RouteEntity?>((ref) async {
  final repo = ref.watch(navigationRepositoryProvider);
  return repo.getActiveRoute();
});

// Reactive Route List
final routesListProvider = FutureProvider<List<RouteEntity>>((ref) async {
  final repo = ref.watch(navigationRepositoryProvider);
  return repo.getAllRoutes();
});

// Route Planner State Controller
final routePlannerControllerProvider =
    NotifierProvider<RoutePlannerController, RoutePlannerState>(
      RoutePlannerController.new,
    );

// Waypoints for a specific route
@riverpod
Future<List<WaypointEntity>> waypointsForRoute(Ref ref, int routeId) async {
  final repo = ref.watch(navigationRepositoryProvider);
  return repo.getWaypointsForRoute(routeId);
}

// NavigationController is auto-generated by riverpod_generator
// via the @riverpod annotation on NavigationController class.
// Use: ref.watch(navigationControllerProvider)
