import 'dart:convert';

import 'package:sakkoja/features/ai/domain/entities/explanation_payload.dart';
import 'package:sakkoja/features/ai/domain/entities/navigation_context.dart';
import 'package:sakkoja/features/ai/domain/entities/weather_insight.dart';
import 'package:sakkoja/features/weather/domain/entities/wave_data.dart';
import 'package:sakkoja/features/weather/domain/entities/weather_data.dart';
import 'package:sakkoja/features/weather/domain/entities/weather_forecast.dart';

/// Builds a structured JSON payload for the AI explanation model.
///
/// This class is pure — no side effects, no I/O. It transforms domain
/// entities into the [ExplanationPayload] format expected by the
/// OpenRouter / ONNX explanation pipeline.
class ExplanationPromptBuilder {
  const ExplanationPromptBuilder();

  /// Hardcoded English system prompt. The AI is instructed to respond
  /// in the user's language via the [language] parameter in the payload.
  static const String systemPrompt =
      'You are an experienced Finnish marine safety advisor. '
      "Given raw weather observations and the user's boat thresholds, "
      "explain IN THE USER'S LANGUAGE why the current conditions are "
      'safe or unsafe. Be concise (2-3 sentences). Do NOT invent data. '
      'If a value is null, do not mention it. Focus on the parameter '
      'that caused the safety status to change. If conditions are good, '
      'reassure briefly. If dangerous, state the hazard clearly and '
      'suggest one practical action.';

  /// Builds the payload from domain entities.
  ///
  /// [language] should be an ISO 639-1 code (e.g. 'en', 'fi', 'sv').
  /// [maxForecastPoints] limits how many forecast points are included
  /// to keep token count low (default 6 = ~6 hours at hourly resolution).
  ExplanationPayload build({
    required WeatherInsight insight,
    required WeatherData? weather,
    required WaveData? wave,
    required List<WeatherForecast> forecasts,
    required SkipperThresholds thresholds,
    required NavigationContext navContext,
    required String language,
    int maxForecastPoints = 6,
  }) {
    return ExplanationPayload(
      meta: ExplanationMeta(
        language: language,
        vesselType: navContext.vesselType.name,
        hasActiveRoute: navContext.hasActiveRoute,
        timestamp: insight.timestamp.toUtc().toIso8601String(),
      ),
      observation: ExplanationObservation(
        windSpeed: weather?.windSpeed,
        windGust: weather?.windGust,
        windDirection: weather?.windDirection,
        waveHeight: wave?.waveHeight,
        wavePeriod: wave?.wavePeriod,
        waveDirection: wave?.waveDirection,
        pressure: weather?.pressure,
        visibility: weather?.visibility,
        temperature: weather?.temperature,
        precipitation: weather?.precipitation,
        cloudCover: weather?.cloudCover,
        humidity: weather?.humidity,
      ),
      thresholds: ExplanationThresholds(
        windYellowMs: thresholds.windYellowMs,
        windOrangeMs: thresholds.windOrangeMs,
        windRedMs: thresholds.windRedMs,
        waveYellowM: thresholds.waveYellowM,
        waveOrangeM: thresholds.waveOrangeM,
        waveRedM: thresholds.waveRedM,
      ),
      status: insight.status.name,
      forecast: _buildForecastList(forecasts, maxForecastPoints),
    );
  }

  /// Serializes the payload to a JSON string suitable for the API body.
  String toJsonString(ExplanationPayload payload) {
    // toJson is generated by freezed/json_serializable.
    // We pretty-print to help the model parse structure.
    const encoder = JsonEncoder.withIndent('  ');
    return encoder.convert(payload.toJson());
  }

  /// Combines system prompt + payload into the full prompt for the model.
  String buildPrompt(ExplanationPayload payload) {
    final jsonPayload = toJsonString(payload);
    return '$systemPrompt\n\n'
        'Respond in language: ${payload.meta.language}\n'
        '--- PAYLOAD ---\n'
        '$jsonPayload\n'
        '--- END PAYLOAD ---';
  }

  List<ExplanationForecast>? _buildForecastList(
    List<WeatherForecast> forecasts,
    int maxPoints,
  ) {
    if (forecasts.isEmpty) return null;

    final limited = forecasts.length > maxPoints
        ? forecasts.sublist(0, maxPoints)
        : forecasts;

    return limited.map((f) {
      return ExplanationForecast(
        timestamp: f.timestamp.toUtc().toIso8601String(),
        windGust: f.windGust,
        precipitation: f.precipitation,
        pressure: f.pressure,
      );
    }).toList();
  }
}
