import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:sakkoja/core/theme/app_palette.dart';
import 'package:sakkoja/core/theme/app_theme.dart';
import 'package:sakkoja/features/ai/domain/entities/weather_insight.dart';

class InsightDetailSheet extends StatelessWidget {
  const InsightDetailSheet({required this.insight, super.key});
  final WeatherInsight insight;

  @override
  Widget build(BuildContext context) {
    final statusColor = _getStatusColor(insight.status);

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: const BoxDecoration(
        color: AppPalette.canvas,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Center(
              child: Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: AppPalette.textSecondary.withValues(alpha: 0.3),
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const SizedBox(height: 20),
            Row(
              children: [
                Icon(
                  _getStatusIcon(insight.status),
                  color: statusColor,
                  size: 28,
                ),
                const SizedBox(width: 12),
                Text(
                  'Safety Status: ${insight.status.name.toUpperCase()}',
                  style: AppTheme.kHeading.copyWith(
                    color: statusColor,
                    fontSize: 18,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Text(
              'Full Explanation',
              style: AppTheme.kBody.copyWith(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            Text(
              insight.advice,
              style: AppTheme.kBody.copyWith(
                height: 1.5,
                color: AppPalette.textPrimary,
              ),
            ),
            if (insight.reasons.isNotEmpty) ...[
              const SizedBox(height: 20),
              Text(
                'Why This Status?',
                style: AppTheme.kBody.copyWith(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 8),
              ...insight.reasons.map((reason) {
                return Padding(
                  padding: const EdgeInsets.only(bottom: 6),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Icon(
                        Icons.arrow_right,
                        size: 18,
                        color: AppPalette.textSecondary,
                      ),
                      const SizedBox(width: 4),
                      Expanded(
                        child: Text(
                          reason,
                          style: AppTheme.kBody.copyWith(
                            height: 1.4,
                            color: AppPalette.textSecondary,
                          ),
                        ),
                      ),
                    ],
                  ),
                );
              }),
            ],
            if (insight.isAIInference) ...[
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: AppPalette.primaryAction.withValues(alpha: 0.1),
                  borderRadius: AppTheme.kBorderRadius,
                  border: Border.all(
                    color: AppPalette.primaryAction.withValues(alpha: 0.3),
                  ),
                ),
                child: Row(
                  children: [
                    const Icon(
                      Icons.auto_awesome,
                      size: 16,
                      color: AppPalette.primaryAction,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'This explanation was generated by an AI model. '
                        'Always verify with official weather sources.',
                        style: AppTheme.kCaption.copyWith(
                          color: AppPalette.primaryAction,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
            const SizedBox(height: 16),
            Text(
              'Generated: ${_formatTimestamp(insight.timestamp)}',
              style: AppTheme.kCaption.copyWith(
                color: AppPalette.textSecondary,
              ),
            ),
            const SizedBox(height: 16),
            InkWell(
              onTap: () {
                Navigator.of(context).pop();
                context.push('/insight-history');
              },
              child: Text(
                'View Full History →',
                style: AppTheme.kBody.copyWith(
                  color: AppPalette.primaryAction,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }

  Color _getStatusColor(SafetyStatus status) {
    switch (status) {
      case SafetyStatus.green:
        return AppPalette.success;
      case SafetyStatus.yellow:
        return AppPalette.warning;
      case SafetyStatus.orange:
        return AppPalette.warning;
      case SafetyStatus.red:
        return AppPalette.danger;
    }
  }

  IconData _getStatusIcon(SafetyStatus status) {
    switch (status) {
      case SafetyStatus.green:
        return Icons.check_circle_outline;
      case SafetyStatus.yellow:
        return Icons.info_outline;
      case SafetyStatus.orange:
        return Icons.warning_amber_rounded;
      case SafetyStatus.red:
        return Icons.dangerous_outlined;
    }
  }

  String _formatTimestamp(DateTime dt) {
    return '${dt.day.toString().padLeft(2, '0')}.${dt.month.toString().padLeft(2, '0')}. ${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}';
  }
}
